v 1.0.0
dr3dnought/balogan pull request #1
Opened 2024-12-06 00:45 UTC by dr3dnought

2024-12-06 12:42 UTC, OlegSadJktu requested changes
в целом не оч понял, какие проблемы решает этот логгер и чем не устраивает логгер от домового

2024-12-08 16:48 UTC, x3noku commented on balogan.go
> +		}(),
Ну вообще, такая штука называется IIFE, иногда такой подход нужен, чтобы вместо того, чтобы плодиить ветвления на верхнем уровне ради одного поля или использовать плохочитаемые тернарники. По-хорошему тут бы саму функцию тоже в круглые скобки обернуть, чтобы нельзя было спутать с объявлением метода

```suggestion
	return &Logger{
		level: level,
		writers: (func() []LogWriter {
			if writer == nil {
				return []LogWriter{NewStdOutLogWriter()}
			}

			return []LogWriter{writer}
		})(),
```

2024-12-12 20:23 UTC, dr3dnought commented on writers.go
> +
в Закрытии не нуждается только std writer, вся остальная запись по определению нуждается в закрытии

2025-07-14 13:40 UTC, dr3dnought commented
v1.0.0 release
Core Logger Functionality:
Complete logging system with 7 log levels (Trace, Debug, Info, Warning, Error, Fatal, Panic)
Formatted logging methods (Debugf, Infof, Warningf, Errorf, etc.)
Level filtering and enabled/disabled checks
Thread-safe concurrent logging support
Multiple writers support with graceful shutdown
Structured Logging:
Fields support with key-value pairs
Multiple formatters: JSON, Logfmt, Key-Value
Convenient methods: WithField(), WithFields(), WithJSON(), WithLogfmt()
Custom field separators support
Prefix System:
Flexible prefix builders for log levels, timestamps, and custom tags
Temporary prefix support for specific log contexts
Chainable prefix configuration
Writer System:
StdOutLogWriter for console output
FileLogWriter for file logging with automatic flushing
Extensible LogWriter interface for custom implementations

2025-07-14 13:40 UTC, merged